/* Generated By:JJTree: Do not edit this line. ASTListDeclaration.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package analyzer.ast;

public
class ASTListDeclaration extends SimpleNode {
  private String value;

  public ASTListDeclaration(int id) {
    super(id);
  }

  public ASTListDeclaration(Parser p, int id) {
    super(p, id);
  }

  public void setValue(final String value) {
    this.value = value;
  }

  public String getValue() { return value; }

  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {

    return
            visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b99a6fa28029883e54f6cccbbe656181 (do not edit this line) */
