/* Generated By:JJTree: Do not edit this line. ASTNormalDeclaration.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package analyzer.ast;

public
class ASTNormalDeclaration extends SimpleNode {
  private String value;

  public ASTNormalDeclaration(int id) {
    super(id);
  }

  public ASTNormalDeclaration(Parser p, int id) {
    super(p, id);
  }

  public void setValue(final String value) {
    this.value = value;
  }

  public String getValue() { return value; }

  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {

    return
            visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=3db8018a42d4d3ff06b7a9c2f333c7bf (do not edit this line) */
